title: An Awesome Course
description: This course is a test for creating courses using GitHub Learning Labs
template:
  repo: an-awesome-course-template
  name: an-awesome-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
